name: Check Terraform

on: 
  push:
  pull_request:

permissions:
  contents: read

jobs:
  tflint:
    runs-on: ubuntu-latest

    name: Lint Terraform

    steps:
      - name: Check out code
        id: checkout
        uses: actions/checkout@v7

      - uses: actions/cache@v6
        id: load-plugins
        name: Cache Plugins
        with:
          path: ~/.tflint.d/plugins
          key: tflint-${{ hashFiles('.tflint.hcl') }}

      - name: Setup TFLint
        id: setup-tflint
        uses: terraform-linters/setup-tflint@6e1e0642c0289bd619021bf6b34e3c08ed1e005a # v6.3.0
        env:
            GITHUB_TOKEN: ${{ github.token }}
        with:
          tflint_version: v0.61.0

      - name: Install Plugins
        id: tflint-plugins
        run: tflint --init

      - name: Lint
        id: tflint
        run: tflint